#!/bin/bash
set -e

HOME=/root

if [ -f AppScalefile ] && /usr/local/appscale-tools/bin/appscale status; then
  exit 0
fi

PRIVATE_IP=$(ifconfig eth0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}')
PUBLIC_IP=$PRIVATE_IP

# If this is an EC2 instance, get its public ip address.
if curl --connect-timeout 2 169.254.169.254 ; then
    PUBLIC_IP=$(curl http://169.254.169.254/2014-11-05/meta-data/public-ipv4)
fi

if [ ! -f AppScalefile ] ; then
    echo "ips_layout :" > AppScalefile
    echo "  controller : ${PRIVATE_IP}" >> AppScalefile
    echo "login : ${PUBLIC_IP}" >> AppScalefile
    echo "test : True" >> AppScalefile
fi

# In the amazon environment, known_hosts seems to get emptied after the install script.
KNOWN_HOSTS_SIZE=$(wc -c < /root/.ssh/known_hosts)
if [ "$KNOWN_HOSTS_SIZE" -eq 1 ] ; then
    ssh-keyscan $PUBLIC_IP $PRIVATE_IP 2> /dev/null >> /root/.ssh/known_hosts
fi

/usr/local/appscale-tools/bin/appscale up

if [ ! -f guestbook.tar.gz ] ; then
    wget -O guestbook.tar.gz http://www.appscale.com/wp-content/uploads/2014/07/guestbook.tar.gz
fi
/usr/local/appscale-tools/bin/appscale deploy guestbook.tar.gz
